# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organlization', '0003_auto_20180321_2132'),
        ('courses', '0002_auto_20180317_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organlization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
