# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-24 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=50, verbose_name='老师告诉你能学到什么'),
        ),
        migrations.AddField(
            model_name='course',
            name='you_needed_konw',
            field=models.CharField(default='', max_length=30, verbose_name='课程须知'),
        ),
    ]
